highlighter: rouge
markdown: kramdown
author: Jujhar Singh
url: https://jujhar.com
permalink: pretty
exclude: ['README.md','_config.yaml','.gitignore','/.git']

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

google_analytics_tracking_id: UA-23579994-1
